dist: focal
language: python
# dist: xenial
# jdk: openjdk8
# os: linux
# group: edge

# arch:
# - arm64
# - s390x
# - amd64
# - ppc64le

# rvm:
# - 2.7.1
# - 2.7.0
# - 2.6.6
# - 2.6.5
# - 2.6.4
# - 2.6.3

python:
- 3.6
- 3.7
- 3.8.2
- 3.8

script:
- uname -a
- ruby -v
- gcc -v
- puthon --version
# - apt install gcc
# - gcc -v
# - java -version
# - dd if=/dev/zero of=file.txt count=1024 bs=40M
# - __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &
# - sleep 6000
# - ruby -v
