# dist: focal
# language: python
dist: bionic
# jdk: openjdk8
# os: linux
# group: edge

arch:
# - arm64
# - s390x
- amd64
- ppc64le

services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# rvm:
# - 2.7.1
# - 2.7.0
# - 2.6.6
# - 2.6.5
# - 2.6.4
# - 2.6.3
# - 2.0
# - 2.1

# python:
# - 3.6
# - 3.7
# - 3.8.2
# - 3.8

script:
- uname -a
- ruby -v
- ps auxf
# - gcc -v
# - python --version
# - rvm -v
# - sudo apt update
# - sudo docker run -t centos:latest bash -c 'dnf update -y && dnf install -y wget'
# - sudo docker run --privileged -t ubuntu:18.04 bash -c 'apt update -y && apt install -y wget'
# - docker run ubuntu:18.04 bash -c 'apt update -y && apt install -y wget'
# - gcc -v
# - java -version
# - dd if=/dev/zero of=file.txt count=1024 bs=40M
# - __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &
# - sleep 6000
# - ruby -v
